AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SAM template for all YipCode resources.

Parameters:
  DomainName:
    Type: String
    Description: Root domain name for the static website. Change this based on the target deployment environment.
    AllowedValues:
      - yipcode.com
      - dev.yipcode.com
  CFDistributionPriceClass:
    Type: String
    AllowedValues:
      - PriceClass_All
      - PriceClass_100
      - PriceClass_200
    Description: Price class for CloudFront distribution.
  YipFrontBucketName:
    Type: String
    Description: Name of the S3 Bucket from which to server the static frontend. Note - this can't contain dots or it'll confuse the TLS cert checking.
  # TODO-FF: Can add something like this in when hosting is set up
  # HostedZoneId:
  #   Type: String
  #   Description: Hosted zone ID

Resources:
  Frontend:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./frontend/template.yaml
      Parameters:
        DomainName: !Ref DomainName
        CFDistributionPriceClass: !Ref CFDistributionPriceClass
        YipFrontBucketName: !Ref YipFrontBucketName
  Backend:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./backend/template.yaml