version=0.1

[default.deploy.parameters]
confirm_changeset=true
tags = "Name=\"yipcode-stack\""
stack_name = "dev-yipcode-backend"
parameter_overrides = ""

[prod.deploy.parameters]
confirm_changeset=true
tags = "Name=\"yipcode-stack\""
stack_name = "prod-yipcode-backend"
parameter_overrides = ""